CREATE TABLE notes (
	id	INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	title	TEXT NOT NULL,
	message	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE TABLE users (
	id INTEGER NOT NULL,
	email TEXT NOT NULL,
	nickname TEXT NOT NULL,
	password TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE TABLE user_role_link (
	id INTEGER NOT NULL,
	id_user INTEGER NOT NULL,
	id_role INTEGER NOT NULL,
	PRIMARY KEY(id AUTOINCREMENT)
);

CREATE TABLE role (
	id INTEGER NOT NULL,
	role TEXT NOT NULL
);

INSERT INTO role (id,role) VALUES (1,"ADMIN");
INSERT INTO role (id,role) VALUES (2,"CLIENT");
INSERT INTO role (id,role) VALUES (3,"NOT_REGISTERED");